#a,b,c,d,e,f,g,h,i,j=sorted(map(int,input().strip().split()))
#print(a,b,c,d,e,f,g,h,i,j)
import math
a,b,c,d,e,f,g,h,i,j=map(int, input().strip().split())
print(j)
print(i)
print(h)
print(g)
print(f)
print(e)
print(d)
print(c)
print(b)
print(a)
